name: Main Workflow

on:
  workflow_call: ./.github/workflows/reusable-workflow.yaml

jobs:
  job1:
    uses: ./.github/workflows/reusable-workflow.yaml

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Mostrar Variable
      run: echo "El valor de MI_VARIABLE es ${{ needs.job1.outputs.output1 }}"
