name: Llamada a otro workflow de otro Repo

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger reusable workflow
      uses: Andres96i/Reusable-actions@v2
      with:
        token: ${{ secrets.REPO_PAT }}
        repository: Andres96i/Reusable-actions
        event-type: activate-workflow

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Mostrar Variable
      run: echo "El valor de MI_VARIABLE es ${{ needs.job1.outputs.output1 }}"

