name: Main-workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.job1.outputs.output1 }}

    steps:
    - name: Activar el reusable workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_PAT }}
        repository: Andres96i/Reusable-actions
        event-type: activate-workflow


  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Descargar resultados
      uses: actions/download-artifact@v2
      with:
        name: results
    - name: Mostrar Variable
      run: echo "El valor de MI_VARIABLE es $MI_VARIABLE"

  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Mostrar Variable
      run: cat results/output1
