name: reusable-workflow

on:
  push:
    branches:
    - features

jobs:
  configurar-y-mostrar:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.configurar-variable.outputs.MI_VARIABLE }}

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar variable
      id: configurar-variable
      run: |
        echo "MI_VARIABLE=Primera Variable" >> $GITHUB_ENV
        echo "MI_VARIABLE=Segunda Variable" >> $GITHUB_OUTPUT

    - name: Mostrar Variable
      run: echo "El valor de MI_VARIABLE es $MI_VARIABLE"
