name: Mostrar Variable

on:
  workflow_dispatch:

jobs:
  mostrar-variable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar variable
      run: echo "MI_VARIABLE=Hola, mundo" >> $GITHUB_ENV

    - name: Mostrar Variable
      run: echo "El valor de MI_VARIABLE es $MI_VARIABLE"
