name: Mostrar Variable

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.configurar-variable.outputs.MI_VARIABLE }}
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar variable
      id: configurar-variable
      run: |
        echo "MI_VARIABLE=Hola, mundo" >> $GITHUB_OUTPUT
        echo "MI_VARIABLE=Hola, mundo2" >> $GITHUB_ENV
      env:
        MI_VARIABLE: ${{ steps.configurar-variable.outputs.MI_VARIABLE }}

    - name: Mostrar Variable
      run: echo "El valor de MI_VARIABLE es $MI_VARIABLE"

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Mostrar Variable
      run: echo "El valor de MI_VARIABLE es ${{ needs.job1.outputs.output1 }}"


